list: $/webbook/blogtaxonomy/models/author/columns.yaml
modelClass: Webbook\BlogTaxonomy\Models\Author
title: Authors
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'webbook/blogtaxonomy/authors/update/:id'
