# ===================================
#  Relation Behavior Config
# ===================================

posts:
    label: webbook.blogtaxonomy::lang.form.fields.posts
    view:
        showSearch: true
        list: post_columns_view.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        list: post_columns_manage.yaml

related_series:
    label: webbook.blogtaxonomy::lang.form.fields.related_series
    view:
        showSearch: true
        list: $/webbook/blogtaxonomy/models/series/columns_short.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        list: $/webbook/blogtaxonomy/models/series/columns_short.yaml
        scope: excludeCurrent