# ===================================
#  Relation Behavior Config
# ===================================

posts:
    label: webbook.blogtaxonomy::lang.form.fields.posts
    view:
        showSearch: true
        list: post_columns_view.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        list: post_columns_manage.yaml

series:
    label: webbook.blogtaxonomy::lang.form.fields.series
    view:
        showSearch: true
        list: series_columns_view.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        list: series_columns_manage.yaml